import "@/styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sidebar from "@/components/shared/sidebar";
import BtnAppBar from "@/components/shared/appBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      
        <div style={{ display: "flex" }}>
          
          <Sidebar />
          <div
            style={{
              flex: "1",
              marginLeft: "240px", // Ancho del Sidebar
            }}
          >
            <BtnAppBar/>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
