-- Creación de la tabla COMPANIAS en MySQL
CREATE TABLE COMPANIAS (
  ID_COMPANIA INT NOT NULL,
  ID_PAIS INT NOT NULL,
  NOMBRE VARCHAR(250) NOT NULL,
  DIRECCION VARCHAR(250) NOT NULL,
  LOGOTIPO VARCHAR(250),
  PRIMARY KEY (ID_COMPANIA),
  FOREIGN KEY (ID_PAIS) REFERENCES PAISES(ID_PAIS)
) ENGINE=InnoDB;

-- Creación de índices
CREATE UNIQUE INDEX COMPA_PK ON COMPANIAS (ID_COMPANIA);
CREATE INDEX COMPA_PAIS_FK_I ON COMPANIAS (ID_PAIS);


ALTER TABLE COMPANIAS
ADD CONSTRAINT FK_ID_PAIS
FOREIGN KEY (ID_PAIS) REFERENCES PAISES(ID_PAIS)
ON DELETE CASCADE ON UPDATE CASCADE;


  /* Variables para información de la sesión */
  DECLARE v_existe_session  INT(24);
  DECLARE v_id_compania     INT(24);
  DECLARE v_id_usuario      INT(24);
  DECLARE v_token           VARCHAR(256);