CREATE TABLE SESIONES (
  ID_SESION   INT NOT NULL,
  ID_COMPANIA INT NOT NULL,
  ID_USUARIO  INT NOT NULL,
  TOKEN VARCHAR(256) NOT NULL,
  FECHA_LOGIN DATE NOT NULL,
  FECHA_LOGOUT DATE,
  FECHA_EXPIRACION DATE NOT NULL,
  DISPOSITIVO VARCHAR(256),
  PRIMARY KEY (ID_SESION),
  FOREIGN KEY (ID_COMPANIA, ID_USUARIO) REFERENCES USUARIOS (ID_COMPANIA, ID_USUARIO)
) ENGINE=InnoDB;

-- Creación de índices
CREATE UNIQUE INDEX SESSION_PK ON SESIONES (ID_SESION);
