CREATE TABLE USUARIOS (
    ID_COMPANIA INT NOT NULL,
    ID_USUARIO INT NOT NULL,
    CORREO_ELECTRONICO VARCHAR(100) NOT NULL,
    CLAVE VARCHAR(1000) NOT NULL,
    NOMBRE VARCHAR(250) NOT NULL,
    FECHA_INICIO DATE NOT NULL,
    FECHA_EXPIRACION DATE,
    ESTADO CHAR(1) NOT NULL,
    ES_ADMINISTRADOR_GENERAL CHAR(1) DEFAULT 'N' NOT NULL,
    TEMA VARCHAR(50),
    IDIOMA VARCHAR(50),
    PRIMARY KEY (ID_COMPANIA, ID_USUARIO),
    CONSTRAINT CHK_COMPANIA_NOT_NULL CHECK (ID_COMPANIA IS NOT NULL),
    CONSTRAINT CHK_USUARIO_NOT_NULL CHECK (ID_USUARIO IS NOT NULL),
    CONSTRAINT CHK_CORREO_NOT_NULL CHECK (CORREO_ELECTRONICO IS NOT NULL),
    CONSTRAINT CHK_CLAVE_NOT_NULL CHECK (CLAVE IS NOT NULL),
    CONSTRAINT CHK_NOMBRE_NOT_NULL CHECK (NOMBRE IS NOT NULL),
    CONSTRAINT CHK_FECHA_INICIO_NOT_NULL CHECK (FECHA_INICIO IS NOT NULL),
    CONSTRAINT CHK_ESTADO_NOT_NULL CHECK (ESTADO IS NOT NULL),
    CONSTRAINT CHK_ES_ADMINISTRADOR_GENERAL_NOT_NULL CHECK (ES_ADMINISTRADOR_GENERAL IS NOT NULL)
) ENGINE=InnoDB;

-- Crear índice único
CREATE UNIQUE INDEX USUARIO_PK ON USUARIOS (ID_COMPANIA, ID_USUARIO);

-- Definición de la clave foránea que referencia a la tabla COMPANIAS
ALTER TABLE USUARIOS ADD CONSTRAINT USUARIO_COMPANIA_FK FOREIGN KEY (ID_COMPANIA) REFERENCES COMPANIAS(ID_COMPANIA);


-- Mario Arita
INSERT INTO USUARIOS
(ID_COMPANIA, ID_USUARIO, CORREO_ELECTRONICO, CLAVE, NOMBRE, FECHA_INICIO, FECHA_EXPIRACION, ESTADO, ES_ADMINISTRADOR_GENERAL, TEMA, IDIOMA)
VALUES (1, 1, 'mario.arita@phonedeheydi.com', 'Mario.arita1', 'Mario Arita', NOW(), NULL, 'A', 'S', NULL, 'ES');

-- Nery Lopez
INSERT INTO USUARIOS
(ID_COMPANIA, ID_USUARIO, CORREO_ELECTRONICO, CLAVE, NOMBRE, FECHA_INICIO, FECHA_EXPIRACION, ESTADO, ES_ADMINISTRADOR_GENERAL, TEMA, IDIOMA)
VALUES (1, 2, 'nery.lopez@email.com', 'clave_secreta2', 'Nery Lopez', NOW(), NULL, 'A', 'N', NULL, 'ES');

-- Miguel Alvarez
INSERT INTO USUARIOS
(ID_COMPANIA, ID_USUARIO, CORREO_ELECTRONICO, CLAVE, NOMBRE, FECHA_INICIO, FECHA_EXPIRACION, ESTADO, ES_ADMINISTRADOR_GENERAL, TEMA, IDIOMA)
VALUES (1, 3, 'miguel.alvarez@email.com', 'clave_secreta3', 'Miguel Alvarez', NOW(), NULL, 'A', 'N', NULL, 'ES');
